// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Ipheidi.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources_en {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_en() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Ipheidi.Resources.AppResources.en", typeof(AppResources_en).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string FilterNom {
            get {
                return ResourceManager.GetString("FilterNom", resourceCulture);
            }
        }
        
        public static string FilterProximite {
            get {
                return ResourceManager.GetString("FilterProximite", resourceCulture);
            }
        }
        
        public static string FilterNotificationActive {
            get {
                return ResourceManager.GetString("FilterNotificationActive", resourceCulture);
            }
        }
        
        public static string GeofencePageTitle {
            get {
                return ResourceManager.GetString("GeofencePageTitle", resourceCulture);
            }
        }
        
        public static string NomLabel {
            get {
                return ResourceManager.GetString("NomLabel", resourceCulture);
            }
        }
        
        public static string NomPlaceHolder {
            get {
                return ResourceManager.GetString("NomPlaceHolder", resourceCulture);
            }
        }
        
        public static string LatitudeLabel {
            get {
                return ResourceManager.GetString("LatitudeLabel", resourceCulture);
            }
        }
        
        public static string LatitudePlaceHolder {
            get {
                return ResourceManager.GetString("LatitudePlaceHolder", resourceCulture);
            }
        }
        
        public static string LongitudeLabel {
            get {
                return ResourceManager.GetString("LongitudeLabel", resourceCulture);
            }
        }
        
        public static string LongitudePlaceHolder {
            get {
                return ResourceManager.GetString("LongitudePlaceHolder", resourceCulture);
            }
        }
        
        public static string ActionEntreeLabel {
            get {
                return ResourceManager.GetString("ActionEntreeLabel", resourceCulture);
            }
        }
        
        public static string ActionSortieLabel {
            get {
                return ResourceManager.GetString("ActionSortieLabel", resourceCulture);
            }
        }
        
        public static string DelaiNotificationLabel {
            get {
                return ResourceManager.GetString("DelaiNotificationLabel", resourceCulture);
            }
        }
        
        public static string MinutesPlaceHolder {
            get {
                return ResourceManager.GetString("MinutesPlaceHolder", resourceCulture);
            }
        }
        
        public static string SecondesPlaceHolder {
            get {
                return ResourceManager.GetString("SecondesPlaceHolder", resourceCulture);
            }
        }
        
        public static string CarteButton {
            get {
                return ResourceManager.GetString("CarteButton", resourceCulture);
            }
        }
        
        public static string GeofenceCreatePageTitle {
            get {
                return ResourceManager.GetString("GeofenceCreatePageTitle", resourceCulture);
            }
        }
        
        public static string NomLieuPlaceHolder {
            get {
                return ResourceManager.GetString("NomLieuPlaceHolder", resourceCulture);
            }
        }
        
        public static string ActiverNotificationLabel {
            get {
                return ResourceManager.GetString("ActiverNotificationLabel", resourceCulture);
            }
        }
        
        public static string SauvegarderBouton {
            get {
                return ResourceManager.GetString("SauvegarderBouton", resourceCulture);
            }
        }
        
        public static string EnregistrerBouton {
            get {
                return ResourceManager.GetString("EnregistrerBouton", resourceCulture);
            }
        }
        
        public static string AnnulerBouton {
            get {
                return ResourceManager.GetString("AnnulerBouton", resourceCulture);
            }
        }
        
        public static string Oui {
            get {
                return ResourceManager.GetString("Oui", resourceCulture);
            }
        }
        
        public static string Non {
            get {
                return ResourceManager.GetString("Non", resourceCulture);
            }
        }
        
        public static string DemarrerBouton {
            get {
                return ResourceManager.GetString("DemarrerBouton", resourceCulture);
            }
        }
        
        public static string ArreterBouton {
            get {
                return ResourceManager.GetString("ArreterBouton", resourceCulture);
            }
        }
        
        public static string EnvoieDonneesBouton {
            get {
                return ResourceManager.GetString("EnvoieDonneesBouton", resourceCulture);
            }
        }
        
        public static string DonneesBouton {
            get {
                return ResourceManager.GetString("DonneesBouton", resourceCulture);
            }
        }
        
        public static string AltitudeLabel {
            get {
                return ResourceManager.GetString("AltitudeLabel", resourceCulture);
            }
        }
        
        public static string DistanceLabel {
            get {
                return ResourceManager.GetString("DistanceLabel", resourceCulture);
            }
        }
        
        public static string OrientationLabel {
            get {
                return ResourceManager.GetString("OrientationLabel", resourceCulture);
            }
        }
        
        public static string PrecisionLabel {
            get {
                return ResourceManager.GetString("PrecisionLabel", resourceCulture);
            }
        }
        
        public static string TempsLabel {
            get {
                return ResourceManager.GetString("TempsLabel", resourceCulture);
            }
        }
        
        public static string SourceEnergieLabel {
            get {
                return ResourceManager.GetString("SourceEnergieLabel", resourceCulture);
            }
        }
        
        public static string NiveauBatterieLabel {
            get {
                return ResourceManager.GetString("NiveauBatterieLabel", resourceCulture);
            }
        }
        
        public static string BatterieUtiliseeLabel {
            get {
                return ResourceManager.GetString("BatterieUtiliseeLabel", resourceCulture);
            }
        }
        
        public static string BatterieStatusLabel {
            get {
                return ResourceManager.GetString("BatterieStatusLabel", resourceCulture);
            }
        }
        
        public static string SupprimerDonneesBouton {
            get {
                return ResourceManager.GetString("SupprimerDonneesBouton", resourceCulture);
            }
        }
        
        public static string ListeDonneesPageTitle {
            get {
                return ResourceManager.GetString("ListeDonneesPageTitle", resourceCulture);
            }
        }
        
        public static string MeilleurNavigationOptionPrecision {
            get {
                return ResourceManager.GetString("MeilleurNavigationOptionPrecision", resourceCulture);
            }
        }
        
        public static string MeilleurOptionPrecision {
            get {
                return ResourceManager.GetString("MeilleurOptionPrecision", resourceCulture);
            }
        }
        
        public static string MoinsDeDixMetresOptionPrecision {
            get {
                return ResourceManager.GetString("MoinsDeDixMetresOptionPrecision", resourceCulture);
            }
        }
        
        public static string CentMetresOptionPrecision {
            get {
                return ResourceManager.GetString("CentMetresOptionPrecision", resourceCulture);
            }
        }
        
        public static string KilometreOptionPrecision {
            get {
                return ResourceManager.GetString("KilometreOptionPrecision", resourceCulture);
            }
        }
        
        public static string TroisKilometreOptionPrecision {
            get {
                return ResourceManager.GetString("TroisKilometreOptionPrecision", resourceCulture);
            }
        }
        
        public static string ModeTestOptionPrecision {
            get {
                return ResourceManager.GetString("ModeTestOptionPrecision", resourceCulture);
            }
        }
        
        public static string MapPageTitle {
            get {
                return ResourceManager.GetString("MapPageTitle", resourceCulture);
            }
        }
        
        public static string CourrielPlaceHolder {
            get {
                return ResourceManager.GetString("CourrielPlaceHolder", resourceCulture);
            }
        }
        
        public static string CourrielLabel {
            get {
                return ResourceManager.GetString("CourrielLabel", resourceCulture);
            }
        }
        
        public static string MotDePasseLabel {
            get {
                return ResourceManager.GetString("MotDePasseLabel", resourceCulture);
            }
        }
        
        public static string MotDePassePlaceHolder {
            get {
                return ResourceManager.GetString("MotDePassePlaceHolder", resourceCulture);
            }
        }
        
        public static string MemoriserLabel {
            get {
                return ResourceManager.GetString("MemoriserLabel", resourceCulture);
            }
        }
        
        public static string AutreCompteBouton {
            get {
                return ResourceManager.GetString("AutreCompteBouton", resourceCulture);
            }
        }
        
        public static string ConnexionBouton {
            get {
                return ResourceManager.GetString("ConnexionBouton", resourceCulture);
            }
        }
        
        public static string RetourBouton {
            get {
                return ResourceManager.GetString("RetourBouton", resourceCulture);
            }
        }
        
        public static string Erreur_LaissezAucunChampVide {
            get {
                return ResourceManager.GetString("Erreur_LaissezAucunChampVide", resourceCulture);
            }
        }
        
        public static string Erreur_MauvaisEmailOuMdp {
            get {
                return ResourceManager.GetString("Erreur_MauvaisEmailOuMdp", resourceCulture);
            }
        }
        
        public static string Erreur_ProblemeConnexionServeur {
            get {
                return ResourceManager.GetString("Erreur_ProblemeConnexionServeur", resourceCulture);
            }
        }
        
        public static string DeconnexionBouton {
            get {
                return ResourceManager.GetString("DeconnexionBouton", resourceCulture);
            }
        }
        
        public static string RegenererBrowserBouton {
            get {
                return ResourceManager.GetString("RegenererBrowserBouton", resourceCulture);
            }
        }
        
        public static string TransfertDonneesWifiLabel {
            get {
                return ResourceManager.GetString("TransfertDonneesWifiLabel", resourceCulture);
            }
        }
        
        public static string EtatDuReseauLabel {
            get {
                return ResourceManager.GetString("EtatDuReseauLabel", resourceCulture);
            }
        }
        
        public static string AccessibleEtatReseau {
            get {
                return ResourceManager.GetString("AccessibleEtatReseau", resourceCulture);
            }
        }
        
        public static string PasAccessibleEtatReseau {
            get {
                return ResourceManager.GetString("PasAccessibleEtatReseau", resourceCulture);
            }
        }
        
        public static string AccessibleViaWifiEtatReseau {
            get {
                return ResourceManager.GetString("AccessibleViaWifiEtatReseau", resourceCulture);
            }
        }
        
        public static string AccessibleViaReseauMobileEtatReseau {
            get {
                return ResourceManager.GetString("AccessibleViaReseauMobileEtatReseau", resourceCulture);
            }
        }
        
        public static string LangueLabel {
            get {
                return ResourceManager.GetString("LangueLabel", resourceCulture);
            }
        }
        
        public static string AccesHoteLabel {
            get {
                return ResourceManager.GetString("AccesHoteLabel", resourceCulture);
            }
        }
        
        public static string LieuxEnregistresBouton {
            get {
                return ResourceManager.GetString("LieuxEnregistresBouton", resourceCulture);
            }
        }
        
        public static string OublierCompteBouton {
            get {
                return ResourceManager.GetString("OublierCompteBouton", resourceCulture);
            }
        }
        
        public static string OublierTousLesComptesBouton {
            get {
                return ResourceManager.GetString("OublierTousLesComptesBouton", resourceCulture);
            }
        }
        
        public static string Alerte_OublierCompteMessage {
            get {
                return ResourceManager.GetString("Alerte_OublierCompteMessage", resourceCulture);
            }
        }
        
        public static string Alerte_OublierTousLesComptesMessage {
            get {
                return ResourceManager.GetString("Alerte_OublierTousLesComptesMessage", resourceCulture);
            }
        }
        
        public static string AucuneAction {
            get {
                return ResourceManager.GetString("AucuneAction", resourceCulture);
            }
        }
        
        public static string Alerte_PlusieurLieuxPositionNouvelleLocalisation_Message {
            get {
                return ResourceManager.GetString("Alerte_PlusieurLieuxPositionNouvelleLocalisation_Message", resourceCulture);
            }
        }
        
        public static string Alerte_PlusieurLieuxPositionNouvelleLocalisation_Title {
            get {
                return ResourceManager.GetString("Alerte_PlusieurLieuxPositionNouvelleLocalisation_Title", resourceCulture);
            }
        }
        
        public static string ChargementLabel {
            get {
                return ResourceManager.GetString("ChargementLabel", resourceCulture);
            }
        }
        
        public static string VitesseLabel {
            get {
                return ResourceManager.GetString("VitesseLabel", resourceCulture);
            }
        }
        
        public static string LocalisationRequisePourApplication {
            get {
                return ResourceManager.GetString("LocalisationRequisePourApplication", resourceCulture);
            }
        }
        
        public static string Alerte_EnvoiePhotoCompleteMessage {
            get {
                return ResourceManager.GetString("Alerte_EnvoiePhotoCompleteMessage", resourceCulture);
            }
        }
        
        public static string ChoisissezEditeurImage {
            get {
                return ResourceManager.GetString("ChoisissezEditeurImage", resourceCulture);
            }
        }
        
        public static string Alerte_ImageUploadHoteInacessibleTitle {
            get {
                return ResourceManager.GetString("Alerte_ImageUploadHoteInacessibleTitle", resourceCulture);
            }
        }
        
        public static string Alerte_ImageUploadHoteInacessibleMessage {
            get {
                return ResourceManager.GetString("Alerte_ImageUploadHoteInacessibleMessage", resourceCulture);
            }
        }
        
        public static string Alerte_ImageUploadPasDeWifiTitle {
            get {
                return ResourceManager.GetString("Alerte_ImageUploadPasDeWifiTitle", resourceCulture);
            }
        }
        
        public static string Alerte_ImageUploadPasDeWifiMessage {
            get {
                return ResourceManager.GetString("Alerte_ImageUploadPasDeWifiMessage", resourceCulture);
            }
        }
        
        public static string CameraFileChooser {
            get {
                return ResourceManager.GetString("CameraFileChooser", resourceCulture);
            }
        }
        
        public static string GaleriePhotoFileChooser {
            get {
                return ResourceManager.GetString("GaleriePhotoFileChooser", resourceCulture);
            }
        }
        
        public static string DocumentFileChooser {
            get {
                return ResourceManager.GetString("DocumentFileChooser", resourceCulture);
            }
        }
        
        public static string ChargeBatteryStatus {
            get {
                return ResourceManager.GetString("ChargeBatteryStatus", resourceCulture);
            }
        }
        
        public static string DechargeBatteryStatus {
            get {
                return ResourceManager.GetString("DechargeBatteryStatus", resourceCulture);
            }
        }
        
        public static string PleineBatteryStatus {
            get {
                return ResourceManager.GetString("PleineBatteryStatus", resourceCulture);
            }
        }
        
        public static string NeChargePasBatteryStatus {
            get {
                return ResourceManager.GetString("NeChargePasBatteryStatus", resourceCulture);
            }
        }
        
        public static string InconnuBatteryStatus {
            get {
                return ResourceManager.GetString("InconnuBatteryStatus", resourceCulture);
            }
        }
        
        public static string CourantPowerSource {
            get {
                return ResourceManager.GetString("CourantPowerSource", resourceCulture);
            }
        }
        
        public static string BatteriePowerSource {
            get {
                return ResourceManager.GetString("BatteriePowerSource", resourceCulture);
            }
        }
        
        public static string UsbPowerSource {
            get {
                return ResourceManager.GetString("UsbPowerSource", resourceCulture);
            }
        }
        
        public static string SansFilPowerSource {
            get {
                return ResourceManager.GetString("SansFilPowerSource", resourceCulture);
            }
        }
        
        public static string AutrePowerSource {
            get {
                return ResourceManager.GetString("AutrePowerSource", resourceCulture);
            }
        }
        
        public static string Alerte_VoulezVousAssociezXCommelieuMessage {
            get {
                return ResourceManager.GetString("Alerte_VoulezVousAssociezXCommelieuMessage", resourceCulture);
            }
        }
        
        public static string ReglageBouton {
            get {
                return ResourceManager.GetString("ReglageBouton", resourceCulture);
            }
        }
        
        public static string Alerte_LocalisationRequiseMessage {
            get {
                return ResourceManager.GetString("Alerte_LocalisationRequiseMessage", resourceCulture);
            }
        }
        
        public static string CopyrightFooter {
            get {
                return ResourceManager.GetString("CopyrightFooter", resourceCulture);
            }
        }
        
        public static string LocalisationSettingTitle {
            get {
                return ResourceManager.GetString("LocalisationSettingTitle", resourceCulture);
            }
        }
        
        public static string LocalisationSettingBouton {
            get {
                return ResourceManager.GetString("LocalisationSettingBouton", resourceCulture);
            }
        }
        
        public static string LocalisationActiveLabel {
            get {
                return ResourceManager.GetString("LocalisationActiveLabel", resourceCulture);
            }
        }
        
        public static string IntervalLocalisationLabel {
            get {
                return ResourceManager.GetString("IntervalLocalisationLabel", resourceCulture);
            }
        }
        
        public static string LocalisationPrecisionLabel {
            get {
                return ResourceManager.GetString("LocalisationPrecisionLabel", resourceCulture);
            }
        }
        
        public static string RayonLabel {
            get {
                return ResourceManager.GetString("RayonLabel", resourceCulture);
            }
        }
        
        public static string RayonPlaceHolder {
            get {
                return ResourceManager.GetString("RayonPlaceHolder", resourceCulture);
            }
        }
        
        public static string AccesGeofenceLabel {
            get {
                return ResourceManager.GetString("AccesGeofenceLabel", resourceCulture);
            }
        }
        
        public static string AccesGeofencePrivate {
            get {
                return ResourceManager.GetString("AccesGeofencePrivate", resourceCulture);
            }
        }
        
        public static string AccesGeofencePublic {
            get {
                return ResourceManager.GetString("AccesGeofencePublic", resourceCulture);
            }
        }
        
        public static string GeofencePublicBouton {
            get {
                return ResourceManager.GetString("GeofencePublicBouton", resourceCulture);
            }
        }
        
        public static string Alerte_RendreGeofencePublic_Title {
            get {
                return ResourceManager.GetString("Alerte_RendreGeofencePublic_Title", resourceCulture);
            }
        }
        
        public static string SuivantBouton {
            get {
                return ResourceManager.GetString("SuivantBouton", resourceCulture);
            }
        }
        
        public static string ContinuerBouton {
            get {
                return ResourceManager.GetString("ContinuerBouton", resourceCulture);
            }
        }
        
        public static string Alerte_RendreXGeofencePublic_Message {
            get {
                return ResourceManager.GetString("Alerte_RendreXGeofencePublic_Message", resourceCulture);
            }
        }
        
        public static string Erreur_Title {
            get {
                return ResourceManager.GetString("Erreur_Title", resourceCulture);
            }
        }
        
        public static string SelectAdresse {
            get {
                return ResourceManager.GetString("SelectAdresse", resourceCulture);
            }
        }
        
        public static string Alerte_SeulUsagerAppareil_Title {
            get {
                return ResourceManager.GetString("Alerte_SeulUsagerAppareil_Title", resourceCulture);
            }
        }
        
        public static string Alerte_SeulUsagerAppareil_Message {
            get {
                return ResourceManager.GetString("Alerte_SeulUsagerAppareil_Message", resourceCulture);
            }
        }
        
        public static string AppareilPartageLabel {
            get {
                return ResourceManager.GetString("AppareilPartageLabel", resourceCulture);
            }
        }
        
        public static string Alerte_Info_SeulUsagerAppareil_Title {
            get {
                return ResourceManager.GetString("Alerte_Info_SeulUsagerAppareil_Title", resourceCulture);
            }
        }
        
        public static string Alerte_Info_SeulUsagerAppareil_Message {
            get {
                return ResourceManager.GetString("Alerte_Info_SeulUsagerAppareil_Message", resourceCulture);
            }
        }
        
        public static string Erreur_AucunServeur {
            get {
                return ResourceManager.GetString("Erreur_AucunServeur", resourceCulture);
            }
        }
    }
}
