// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Ipheidi.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Ipheidi.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string FilterNom {
            get {
                return ResourceManager.GetString("FilterNom", resourceCulture);
            }
        }
        
        internal static string FilterProximite {
            get {
                return ResourceManager.GetString("FilterProximite", resourceCulture);
            }
        }
        
        internal static string FilterNotificationActive {
            get {
                return ResourceManager.GetString("FilterNotificationActive", resourceCulture);
            }
        }
        
        internal static string GeofencePageTitle {
            get {
                return ResourceManager.GetString("GeofencePageTitle", resourceCulture);
            }
        }
        
        internal static string NomLabel {
            get {
                return ResourceManager.GetString("NomLabel", resourceCulture);
            }
        }
        
        internal static string NomPlaceHolder {
            get {
                return ResourceManager.GetString("NomPlaceHolder", resourceCulture);
            }
        }
        
        internal static string LatitudeLabel {
            get {
                return ResourceManager.GetString("LatitudeLabel", resourceCulture);
            }
        }
        
        internal static string LatitudePlaceHolder {
            get {
                return ResourceManager.GetString("LatitudePlaceHolder", resourceCulture);
            }
        }
        
        internal static string LongitudeLabel {
            get {
                return ResourceManager.GetString("LongitudeLabel", resourceCulture);
            }
        }
        
        internal static string LongitudePlaceHolder {
            get {
                return ResourceManager.GetString("LongitudePlaceHolder", resourceCulture);
            }
        }
        
        internal static string ActionEntreeLabel {
            get {
                return ResourceManager.GetString("ActionEntreeLabel", resourceCulture);
            }
        }
        
        internal static string ActionSortieLabel {
            get {
                return ResourceManager.GetString("ActionSortieLabel", resourceCulture);
            }
        }
        
        internal static string DelaiNotificationLabel {
            get {
                return ResourceManager.GetString("DelaiNotificationLabel", resourceCulture);
            }
        }
        
        internal static string MinutesPlaceHolder {
            get {
                return ResourceManager.GetString("MinutesPlaceHolder", resourceCulture);
            }
        }
        
        internal static string SecondesPlaceHolder {
            get {
                return ResourceManager.GetString("SecondesPlaceHolder", resourceCulture);
            }
        }
        
        internal static string CarteButton {
            get {
                return ResourceManager.GetString("CarteButton", resourceCulture);
            }
        }
        
        internal static string GeofenceCreatePageTitle {
            get {
                return ResourceManager.GetString("GeofenceCreatePageTitle", resourceCulture);
            }
        }
        
        internal static string NomLieuPlaceHolder {
            get {
                return ResourceManager.GetString("NomLieuPlaceHolder", resourceCulture);
            }
        }
        
        internal static string ActiverNotificationLabel {
            get {
                return ResourceManager.GetString("ActiverNotificationLabel", resourceCulture);
            }
        }
        
        internal static string SauvegarderBouton {
            get {
                return ResourceManager.GetString("SauvegarderBouton", resourceCulture);
            }
        }
        
        internal static string EnregistrerBouton {
            get {
                return ResourceManager.GetString("EnregistrerBouton", resourceCulture);
            }
        }
        
        internal static string AnnulerBouton {
            get {
                return ResourceManager.GetString("AnnulerBouton", resourceCulture);
            }
        }
        
        internal static string Oui {
            get {
                return ResourceManager.GetString("Oui", resourceCulture);
            }
        }
        
        internal static string Non {
            get {
                return ResourceManager.GetString("Non", resourceCulture);
            }
        }
        
        internal static string DemarrerBouton {
            get {
                return ResourceManager.GetString("DemarrerBouton", resourceCulture);
            }
        }
        
        internal static string ArreterBouton {
            get {
                return ResourceManager.GetString("ArreterBouton", resourceCulture);
            }
        }
        
        internal static string EnvoieDonneesBouton {
            get {
                return ResourceManager.GetString("EnvoieDonneesBouton", resourceCulture);
            }
        }
        
        internal static string DonneesBouton {
            get {
                return ResourceManager.GetString("DonneesBouton", resourceCulture);
            }
        }
        
        internal static string AltitudeLabel {
            get {
                return ResourceManager.GetString("AltitudeLabel", resourceCulture);
            }
        }
        
        internal static string DistanceLabel {
            get {
                return ResourceManager.GetString("DistanceLabel", resourceCulture);
            }
        }
        
        internal static string OrientationLabel {
            get {
                return ResourceManager.GetString("OrientationLabel", resourceCulture);
            }
        }
        
        internal static string PrecisionLabel {
            get {
                return ResourceManager.GetString("PrecisionLabel", resourceCulture);
            }
        }
        
        internal static string TempsLabel {
            get {
                return ResourceManager.GetString("TempsLabel", resourceCulture);
            }
        }
        
        internal static string SourceEnergieLabel {
            get {
                return ResourceManager.GetString("SourceEnergieLabel", resourceCulture);
            }
        }
        
        internal static string NiveauBatterieLabel {
            get {
                return ResourceManager.GetString("NiveauBatterieLabel", resourceCulture);
            }
        }
        
        internal static string BatterieUtiliseeLabel {
            get {
                return ResourceManager.GetString("BatterieUtiliseeLabel", resourceCulture);
            }
        }
        
        internal static string BatterieStatusLabel {
            get {
                return ResourceManager.GetString("BatterieStatusLabel", resourceCulture);
            }
        }
        
        internal static string SupprimerDonneesBouton {
            get {
                return ResourceManager.GetString("SupprimerDonneesBouton", resourceCulture);
            }
        }
        
        internal static string ListeDonneesPageTitle {
            get {
                return ResourceManager.GetString("ListeDonneesPageTitle", resourceCulture);
            }
        }
        
        internal static string MeilleurNavigationOptionPrecision {
            get {
                return ResourceManager.GetString("MeilleurNavigationOptionPrecision", resourceCulture);
            }
        }
        
        internal static string MeilleurOptionPrecision {
            get {
                return ResourceManager.GetString("MeilleurOptionPrecision", resourceCulture);
            }
        }
        
        internal static string MoinsDeDixMetresOptionPrecision {
            get {
                return ResourceManager.GetString("MoinsDeDixMetresOptionPrecision", resourceCulture);
            }
        }
        
        internal static string CentMetresOptionPrecision {
            get {
                return ResourceManager.GetString("CentMetresOptionPrecision", resourceCulture);
            }
        }
        
        internal static string KilometreOptionPrecision {
            get {
                return ResourceManager.GetString("KilometreOptionPrecision", resourceCulture);
            }
        }
        
        internal static string TroisKilometreOptionPrecision {
            get {
                return ResourceManager.GetString("TroisKilometreOptionPrecision", resourceCulture);
            }
        }
        
        internal static string ModeTestOptionPrecision {
            get {
                return ResourceManager.GetString("ModeTestOptionPrecision", resourceCulture);
            }
        }
        
        internal static string MapPageTitle {
            get {
                return ResourceManager.GetString("MapPageTitle", resourceCulture);
            }
        }
        
        internal static string CourrielPlaceHolder {
            get {
                return ResourceManager.GetString("CourrielPlaceHolder", resourceCulture);
            }
        }
        
        internal static string CourrielLabel {
            get {
                return ResourceManager.GetString("CourrielLabel", resourceCulture);
            }
        }
        
        internal static string MotDePasseLabel {
            get {
                return ResourceManager.GetString("MotDePasseLabel", resourceCulture);
            }
        }
        
        internal static string MotDePassePlaceHolder {
            get {
                return ResourceManager.GetString("MotDePassePlaceHolder", resourceCulture);
            }
        }
        
        internal static string MemoriserLabel {
            get {
                return ResourceManager.GetString("MemoriserLabel", resourceCulture);
            }
        }
        
        internal static string AutreCompteBouton {
            get {
                return ResourceManager.GetString("AutreCompteBouton", resourceCulture);
            }
        }
        
        internal static string ConnexionBouton {
            get {
                return ResourceManager.GetString("ConnexionBouton", resourceCulture);
            }
        }
        
        internal static string RetourBouton {
            get {
                return ResourceManager.GetString("RetourBouton", resourceCulture);
            }
        }
        
        internal static string Erreur_LaissezAucunChampVide {
            get {
                return ResourceManager.GetString("Erreur_LaissezAucunChampVide", resourceCulture);
            }
        }
        
        internal static string Erreur_MauvaisEmailOuMdp {
            get {
                return ResourceManager.GetString("Erreur_MauvaisEmailOuMdp", resourceCulture);
            }
        }
        
        internal static string Erreur_ProblemeConnexionServeur {
            get {
                return ResourceManager.GetString("Erreur_ProblemeConnexionServeur", resourceCulture);
            }
        }
        
        internal static string DeconnexionBouton {
            get {
                return ResourceManager.GetString("DeconnexionBouton", resourceCulture);
            }
        }
        
        internal static string RegenererBrowserBouton {
            get {
                return ResourceManager.GetString("RegenererBrowserBouton", resourceCulture);
            }
        }
        
        internal static string TransfertDonneesWifiLabel {
            get {
                return ResourceManager.GetString("TransfertDonneesWifiLabel", resourceCulture);
            }
        }
        
        internal static string EtatDuReseauLabel {
            get {
                return ResourceManager.GetString("EtatDuReseauLabel", resourceCulture);
            }
        }
        
        internal static string AccessibleEtatReseau {
            get {
                return ResourceManager.GetString("AccessibleEtatReseau", resourceCulture);
            }
        }
        
        internal static string PasAccessibleEtatReseau {
            get {
                return ResourceManager.GetString("PasAccessibleEtatReseau", resourceCulture);
            }
        }
        
        internal static string AccessibleViaWifiEtatReseau {
            get {
                return ResourceManager.GetString("AccessibleViaWifiEtatReseau", resourceCulture);
            }
        }
        
        internal static string AccessibleViaReseauMobileEtatReseau {
            get {
                return ResourceManager.GetString("AccessibleViaReseauMobileEtatReseau", resourceCulture);
            }
        }
        
        internal static string LangueLabel {
            get {
                return ResourceManager.GetString("LangueLabel", resourceCulture);
            }
        }
        
        internal static string AccesHoteLabel {
            get {
                return ResourceManager.GetString("AccesHoteLabel", resourceCulture);
            }
        }
        
        internal static string LieuxEnregistresBouton {
            get {
                return ResourceManager.GetString("LieuxEnregistresBouton", resourceCulture);
            }
        }
        
        internal static string OublierCompteBouton {
            get {
                return ResourceManager.GetString("OublierCompteBouton", resourceCulture);
            }
        }
        
        internal static string OublierTousLesComptesBouton {
            get {
                return ResourceManager.GetString("OublierTousLesComptesBouton", resourceCulture);
            }
        }
        
        internal static string _ {
            get {
                return ResourceManager.GetString("", resourceCulture);
            }
        }
    }
}
